### PR TITLE
Update server name

### PR DESCRIPTION
**Pull request by sapzape**
Update the server name to match the meaning of the project.

### CODE REVIEW

**Review by xissy — APPROVED** [review]
👍 thanks!

**Comment by sapzape** [comment]
@xissy i can't merge because i don't have permission (maybe) 😢

**Comment by xissy** [comment]
> @xissy i can't merge because i don't have permission (maybe) 😢

@sapzape ah my bad! just invited you as a member of ohmygrpc org. can you confirm that you are able to merge after accepting the invitation?

image

**Comment by xissy** [comment]
let me merge~

**Pull request merged**
